version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=mlflow_user
      - POSTGRES_PASSWORD=mlflow_senha_segura
      - POSTGRES_DB=mlflow_db
    # Removi o mapeamento de porta 5432 para o mundo externo por segurança. 
    # O MLflow fala com o DB por dentro da rede do docker.
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.11.1
    restart: always
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-1
    command: >
      sh -c "pip install psycopg2-binary boto3 && 
             apt-get update &&
             apt-get install -y libgomp1 &&
             mlflow server --backend-store-uri postgresql://mlflow_user:mlflow_senha_segura@db:5432/mlflow_db --default-artifact-root s3://financial-asset-price-forecasting-495599733085-us-east-1-an/mlflow-artifacts/ --host 0.0.0.0"
      
    depends_on:
      - db

volumes:
  postgres_data: