version: '3.8'

services:
  finance-api:
    build: .
    container_name: finance-api
    ports:
      - "8080:8080"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - S3_BUCKET_NAME=financial-asset-price-forecasting-495599733085-us-east-1-an
    # Garante que a API volte a ligar sozinha caso a máquina reinicie ou dê crash
    restart: always